// export const environment = {
//   production: true,
//   EMAILJS_SERVICE_ID: 'service_2trf6u1',
//   EMAILJS_TEMPLATE_ID: 'template_b9dfigf',
//   EMAILJS_AUTO_REPLY_TEMPLATE_ID: 'template_rt17whj',
//   EMAILJS_PUBLIC_KEY: '1PX2P6dWBFkvJm3qZ',
//   GOOGLE_ANALYTICS_ID: 'G-MZYDMBW5VN',
// };

export const environment = {
  production: true,
  EMAILJS_SERVICE_ID: '<EMAILJS_SERVICE_ID>',
  EMAILJS_TEMPLATE_ID: '<EMAILJS_TEMPLATE_ID>',
  EMAILJS_AUTO_REPLY_TEMPLATE_ID: '<EMAILJS_AUTO_REPLY_TEMPLATE_ID>',
  EMAILJS_PUBLIC_KEY: '<EMAILJS_PUBLIC_KEY>',
  GOOGLE_ANALYTICS_ID: '<GOOGLE_ANALYTICS_ID>',
};
